# Generated by Django 3.2.9 on 2021-12-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customusermodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_pic',
            field=models.ImageField(upload_to='images/profile_pic'),
        ),
    ]
